# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Test BeChatted iOS app
      run: xcodebuild clean build test -workspace BeChatted.xcworkspace -scheme "BeChatted" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=Any iOS Simulator Device" ONLY_ACTIVE_ARCH=YES
    - name: Build and Test BeChattedAuth
      run: xcodebuild clean build test -project BeChattedAuth/BeChattedAuth.xcodeproj -scheme "BeChattedAuth" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
    - name: Build and Test BeChattedUserInputValidation
      run: xcodebuild clean build test -project BeChattedUserInputValidation/BeChattedUserInputValidation.xcodeproj -scheme "BeChattedUserInputValidation" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
